import { notFound } from "next/navigation";
import Link from "next/link";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { audit } from "@/lib/audit";
import { format } from "date-fns";
import { formatPrice } from "@/lib/utils";
import { CLINIC } from "@/lib/clinic";
import { parseHistory, historyLabel } from "@/lib/intake";

// Server-rendered, audit-logged clinical record. Designed for browser
// "Print / Save as PDF" — see the @media print rules at the top.
//
// Audit footprint: every page load writes a VIEW_CLIENT_RECORD entry, so
// staff access is traceable for compliance reviews. The page itself is
// gated to STAFF / ADMIN roles only.

const sydFmt = new Intl.DateTimeFormat("en-AU", {
  timeZone: "Australia/Sydney",
  dateStyle: "medium",
  timeStyle: "short",
});

export default async function ClientClinicalRecord({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const session = (await auth())!;
  if (session.user.role !== "STAFF" && session.user.role !== "ADMIN") {
    notFound();
  }
  const { id } = await params;

  const client = await db.user.findUnique({
    where: { id },
    include: {
      intakeForms: { orderBy: { signedAt: "desc" } },
      consentRecords: { orderBy: { createdAt: "desc" } },
      bookings: {
        orderBy: { startsAt: "desc" },
        include: {
          service: true,
          variant: true,
          therapist: { include: { user: true } },
          noteAuthor: { select: { name: true } },
        },
      },
    },
  });
  if (!client) notFound();

  await audit({
    userId: session.user.id,
    action: "VIEW_CLIENT_RECORD",
    resource: `User:${id}`,
    metadata: {
      clientName: client.name,
      totalBookings: client.bookings.length,
    },
  });

  const generatedAt = new Date();
  const latestIntake = client.intakeForms[0];
  const latestConsent = client.consentRecords[0];

  return (
    <>
      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { background: white !important; }
          .booking-entry { page-break-inside: avoid; }
          .section-header { page-break-after: avoid; }
          .record-container { padding: 0 !important; max-width: none !important; }
        }
        @media screen {
          .record-container { max-width: 800px; margin: 0 auto; padding: 2rem; background: white; color: black; }
          .record-container * { color: black; }
        }
      `}</style>

      <div className="no-print bg-muted/30 border-b p-3">
        <div className="max-w-[800px] mx-auto flex items-center justify-between">
          <Link
            href={`/staff/clients/${id}`}
            className="text-sm text-muted-foreground hover:text-foreground"
          >
            \u2190 Back to client profile
          </Link>
          <p className="text-sm text-muted-foreground">
            Press <kbd className="rounded border px-1 text-xs">Ctrl/Cmd+P</kbd> to print or save as PDF
          </p>
        </div>
      </div>

      <div className="record-container">
        <header className="border-b-2 pb-4 mb-6">
          <p className="text-xs uppercase tracking-wider text-gray-600">{CLINIC.name}</p>
          <h1 className="text-2xl font-bold mt-1">Clinical record</h1>
          <h2 className="text-xl mt-2">{client.name}</h2>
          <p className="text-xs text-gray-600 mt-2">
            Generated by {session.user.name} on {sydFmt.format(generatedAt)} (Sydney time)
          </p>
          <p className="text-xs text-gray-600 mt-1">
            Access to this record is logged in the audit trail.
          </p>
        </header>

        <section className="mb-6">
          <h3 className="text-sm font-bold uppercase tracking-wider text-gray-700 mb-3 section-header">
            Client details
          </h3>
          <Field label="Name" value={client.name} />
          <Field label="Date of birth" value={client.dob ? format(client.dob, "d MMM yyyy") : "\u2014"} />
          <Field label="Phone" value={client.phone ?? "\u2014"} />
          <Field label="Email" value={client.email} />
          <Field
            label="Address"
            value={
              [client.addressLine1, client.suburb, client.stateRegion, client.postcode]
                .filter(Boolean)
                .join(", ") || "\u2014"
            }
          />
          <Field
            label="GP"
            value={
              [client.gpName, client.gpClinic].filter(Boolean).join(" \u2014 ") || "\u2014"
            }
          />
          <Field label="GP phone" value={client.gpPhone ?? "\u2014"} />
          <Field
            label="Member since"
            value={format(client.createdAt, "d MMM yyyy")}
          />
        </section>

        <section className="mb-6">
          <h3 className="text-sm font-bold uppercase tracking-wider text-gray-700 mb-3 section-header">
            Health intake form
            {latestIntake
              ? ` \u2014 submitted ${format(latestIntake.signedAt ?? latestIntake.createdAt, "d MMM yyyy")}`
              : ""}
          </h3>
          {latestIntake ? (
            <>
              <Field
                label="Pregnancy"
                value={
                  latestIntake.pregnancy
                    ? latestIntake.pregnancyWeeks
                      ? `Yes \u2014 ${latestIntake.pregnancyWeeks} weeks`
                      : "Yes"
                    : "No"
                }
              />
              <Field
                label="Medical history"
                value={
                  parseHistory(latestIntake.medicalHistory)
                    .map(historyLabel)
                    .join(", ") || "None reported"
                }
              />
              <Field
                label="Other conditions"
                value={latestIntake.medicalConditions ?? "\u2014"}
              />
              <Field
                label="Medications"
                value={latestIntake.medications ?? "\u2014"}
              />
              <Field
                label="Allergies"
                value={latestIntake.allergies ?? "\u2014"}
              />
              <Field
                label="Pain location"
                value={latestIntake.painLocation ?? "\u2014"}
              />
              <Field
                label="Pain scale (0-10)"
                value={
                  latestIntake.painScale != null ? String(latestIntake.painScale) : "\u2014"
                }
              />
              <Field label="Pain onset" value={latestIntake.painOnset ?? "\u2014"} />
              <Field
                label="Pain history"
                value={latestIntake.painHistory ?? "\u2014"}
              />
              <Field
                label="Treatment goals"
                value={latestIntake.treatmentGoals ?? "\u2014"}
              />
              <Field
                label="Injuries / areas to avoid"
                value={latestIntake.injuries ?? "\u2014"}
              />
              <Field
                label="Emergency contact"
                value={
                  [
                    latestIntake.emergencyContactName,
                    latestIntake.emergencyContactRelationship,
                    latestIntake.emergencyContactPhone,
                  ]
                    .filter(Boolean)
                    .join(" \u00b7 ") || "\u2014"
                }
              />
              {client.intakeForms.length > 1 && (
                <p className="text-xs text-gray-600 mt-2 italic">
                  Earlier intake submissions: {client.intakeForms.length - 1}{" "}
                  (oldest from{" "}
                  {format(
                    client.intakeForms[client.intakeForms.length - 1].signedAt ??
                      client.intakeForms[client.intakeForms.length - 1].createdAt,
                    "d MMM yyyy",
                  )}
                  )
                </p>
              )}
            </>
          ) : (
            <p className="text-sm text-gray-600 italic">No intake on file.</p>
          )}
        </section>

        <section className="mb-6">
          <h3 className="text-sm font-bold uppercase tracking-wider text-gray-700 mb-3 section-header">
            Consent
          </h3>
          {latestConsent ? (
            <>
              <Field
                label="Latest consent"
                value={`${format(latestConsent.createdAt, "d MMM yyyy, h:mm a")} from IP ${latestConsent.ipAddress ?? "(not recorded)"}`}
              />
              <Field
                label="Total consent records"
                value={String(client.consentRecords.length)}
              />
            </>
          ) : (
            <p className="text-sm text-gray-600 italic">No consent records on file.</p>
          )}
        </section>

        <section className="mb-6">
          <h3 className="text-sm font-bold uppercase tracking-wider text-gray-700 mb-3 section-header">
            Treatment history \u2014 {client.bookings.length}{" "}
            {client.bookings.length === 1 ? "booking" : "bookings"}
          </h3>
          {client.bookings.length === 0 ? (
            <p className="text-sm text-gray-600 italic">No bookings.</p>
          ) : (
            <div className="space-y-4">
              {client.bookings.map((b) => (
                <div
                  key={b.id}
                  className="booking-entry border rounded-md p-4"
                >
                  <div className="mb-2 pb-2 border-b">
                    <p className="font-semibold">
                      {format(b.startsAt, "EEEE d MMM yyyy")}
                    </p>
                    <p className="text-xs text-gray-600">
                      {format(b.startsAt, "h:mm a")} \u2013{" "}
                      {format(b.endsAt, "h:mm a")} ({b.variant.durationMin}{" "}
                      min) \u00b7 {b.service.name} \u00b7{" "}
                      {b.therapist?.user.name ?? "Unassigned"} \u00b7{" "}
                      {formatPrice(b.priceCentsAtBooking)} \u00b7 {b.status}
                      {b.claimWithHealthFund ? " \u00b7 Health fund claim" : ""}
                    </p>
                    <p className="text-xs text-gray-600 mt-0.5 font-mono">
                      Ref: {b.reference}
                    </p>
                  </div>

                  {b.noteSubjective ||
                  b.noteObjective ||
                  b.noteAssessment ||
                  b.notePlan ||
                  b.noteAreasTreated ||
                  b.noteTechniques ||
                  b.noteOutcome ? (
                    <div className="space-y-2 text-sm">
                      <NoteRow label="S \u2014 Subjective" value={b.noteSubjective} />
                      <NoteRow label="O \u2014 Objective" value={b.noteObjective} />
                      <NoteRow label="A \u2014 Assessment" value={b.noteAssessment} />
                      <NoteRow label="P \u2014 Plan" value={b.notePlan} />
                      <NoteRow label="Areas treated" value={b.noteAreasTreated} />
                      <NoteRow label="Techniques" value={b.noteTechniques} />
                      <NoteRow label="Outcome" value={b.noteOutcome} />
                      {b.noteUpdatedAt && (
                        <p className="text-xs text-gray-600 italic mt-2">
                          Notes by {b.noteAuthor?.name ?? "unknown"} \u00b7{" "}
                          {sydFmt.format(b.noteUpdatedAt)}
                        </p>
                      )}
                    </div>
                  ) : (
                    <p className="text-sm text-gray-500 italic">
                      No clinical notes recorded.
                    </p>
                  )}

                  {b.notes && (
                    <div className="mt-3 pt-2 border-t text-sm">
                      <p className="text-xs uppercase tracking-wider text-gray-600 mb-1">
                        General notes
                      </p>
                      <p className="whitespace-pre-wrap">{b.notes}</p>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </section>

        <footer className="mt-8 pt-4 border-t text-xs text-gray-600">
          <p>
            End of record. Generated {sydFmt.format(generatedAt)} by{" "}
            {session.user.name}.
          </p>
          <p className="mt-1">
            {CLINIC.name}
            {CLINIC.phone ? ` \u00b7 ${CLINIC.phone}` : ""}
            {CLINIC.email ? ` \u00b7 ${CLINIC.email}` : ""}
          </p>
        </footer>
      </div>
    </>
  );
}

function Field({
  label,
  value,
}: {
  label: string;
  value: string | number | React.ReactNode;
}) {
  return (
    <div className="flex gap-4 mb-1.5 text-sm">
      <span className="font-medium min-w-[180px] text-gray-700">{label}:</span>
      <span className="whitespace-pre-wrap">{value}</span>
    </div>
  );
}

function NoteRow({ label, value }: { label: string; value: string | null }) {
  if (!value) return null;
  return (
    <div>
      <p className="font-medium text-xs uppercase tracking-wider text-gray-600 mb-0.5">
        {label}
      </p>
      <p className="whitespace-pre-wrap pl-2">{value}</p>
    </div>
  );
}
